version: '3'
services:
#  db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=bodb
#    container_name: postgres-db
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - "54320:5432"
  greta.bo.worker:
    image: greta.bo.broker
    build:
      context: .
      dockerfile: src/Greta.BO.Api/Dockerfile
