using System.Text.Json.Serialization;

namespace Greta.BO.Wix.Models;

public class OnlineWixProdCreateResponse
{
    [JsonPropertyName("product")]
    public OnlineWixProduct OnlineWixProduct { get; set; }
}

public class OnlineWixProduct
{
    [JsonPropertyName("id")] public string Id { get; set; }
    [JsonPropertyName("name")] public string Name { get; set; }

    [JsonPropertyName("slug")] public string Slug { get; set; }

    [JsonPropertyName("visible")] public bool Visible { get; set; }

    [JsonPropertyName("productType")] public string ProductType { get; set; }

    [JsonPropertyName("description")] public string Description { get; set; }

    // [JsonPropertyName("weightRange")]
    // public Range WeightRange { get; set; }

    // [JsonPropertyName("stock")]
    // public Stock Stock { get; set; }

    [JsonPropertyName("price")] public WixConvertedPriceData Price { get; set; }

    [JsonPropertyName("priceData")] public WixConvertedPriceData PriceData { get; set; }

    // [JsonPropertyName("convertedPriceData")]
    // public ConvertedPriceData ConvertedPriceData { get; set; }

    // [JsonPropertyName("priceRange")]
    // public Range PriceRange { get; set; }

    // [JsonPropertyName("costRange")]
    // public Range CostRange { get; set; }

    [JsonPropertyName("additionalInfoSections")]
    public object[] AdditionalInfoSections { get; set; }

    // [JsonPropertyName("ribbons")]
    // public Ribbon[] Ribbons { get; set; }

    [JsonPropertyName("media")] public WixMedia Media { get; set; }

    [JsonPropertyName("customTextFields")] public object[] CustomTextFields { get; set; }

    // [JsonPropertyName("manageVariants")]
    // public bool ManageVariants { get; set; }

    // [JsonPropertyName("productOptions")]
    // public ProductOption[] ProductOptions { get; set; }

    // [JsonPropertyName("productPageUrl")]
    // public ProductPageUrl ProductPageUrl { get; set; }

    [JsonPropertyName("numericId")] public string NumericId { get; set; }

    [JsonPropertyName("inventoryItemId")] public Guid InventoryItemId { get; set; }

    // [JsonPropertyName("discount")] public WixDiscount Discount { get; set; }

    //only one collection on our system
    [JsonPropertyName("collectionIds")] public string[] CollectionIds { get; set; }

    // [JsonPropertyName("variants")]
    // public VariantElement[] Variants { get; set; }

    [JsonPropertyName("lastUpdated")] public DateTimeOffset LastUpdated { get; set; }

    [JsonPropertyName("createdDate")] public DateTimeOffset CreatedDate { get; set; }

    [JsonPropertyName("ribbon")] public string Ribbon { get; set; }

    [JsonPropertyName("brand")] public string Brand { get; set; }
}

public class WixConvertedPriceData
{
    [JsonPropertyName("currency")] public string Currency { get; set; }

    [JsonPropertyName("price")] public double Price { get; set; }

    [JsonPropertyName("discountedPrice")] public double DiscountedPrice { get; set; }

    // [JsonPropertyName("formatted")]
    // public Formatted Formatted { get; set; }
}

public class WixDiscount
{
    [JsonPropertyName("type")] public string Type { get; set; }

    [JsonPropertyName("value")] public long Value { get; set; }
}

public class OnlineWixGetProductResponse
{
    [JsonPropertyName("product")]
    public List<OnlineWixProduct> OnlineWixProduct { get; set; }
}

// Generated by https://quicktype.io



    public partial class AddMedia
    {
        [JsonPropertyName("media")]
        public Media[] Media { get; set; }
    }

    public partial class Media
    {
        [JsonPropertyName("mediaId")]
        public string MediaId { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }

        [JsonPropertyName("choice")]
        public Choice Choice { get; set; }
    }

    public partial class Choice
    {
        [JsonPropertyName("option")]
        public string Option { get; set; }

        [JsonPropertyName("choice")]
        public string ChoiceChoice { get; set; }
    }
