name: Build & Deploy Docs

on:
#  push:
#    branches: [ "develop" ]
#  pull_request:
#    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
        
      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx_project/docfx.json
     
      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            _site/
            captain-definition
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: 'https://captain.gretadev.gretatest.com/'
          app: 'bodocs'
          token: '${{ secrets.BOAPP_TOKEN }}'